language: minimal

sudo: false

env:
  global:
    # Doctr deploy key for oceanhackweek/oceanhackweek.github.io
    - secure: "OXn6IPTYhA/SXmmztmp0uaOUF2y7jq7Wj5eXhylrTpI7/8ayi0huS/urxiRW+mawDwtCDNC1rGS+K6+cORNpkh7LI9PW1eIhNfXeKITYo89HfP7R7ozsL8EQ0xPBb1CR1bfEM3G5Jxo5CcdwmRpR6ahQqaB7Mm+aidXUI0an2eZ7QDthZfKd10tWkfTOQY2jbNuyHJmXfLpx2FhUEUNnBFlcqdSOZWmqv5hX0AfepHW/J5LOu4cqBwfxZNeeNHBfLjHMqBHL9muaaf/TuY78pt2XOcCjZk+ww2+SVxbY3w5gTdGrtbY56pUthbMY/5sBWftz5LAyVG9xp54JE+J3pDPBethwqDMENRsbTOG+eQ0ygEXlP0UbUpkZ4JInsvILzpsDUOSfhsl2GZqBOvpSIeEKXiMsJu3blU14+z+K/B7lhvz8cCeJ24O5LeqTepKwO57Q2sVAu1dRoGV1SQwcJbq8jkqOVePbpCHgn8Yl0YNu2NJARAfntQy7W84GHqlGkhdOwT0FSBi1B4PNunI6/AeJz7O+1vph5McSETTkncGJajgH1ibhjr2UypzGzGz548ByqAgDRT32pW/e5vYmXQnpSOhPsDQDMiONAcqJkJtWSY2RYLkx8jh21AseS/mKxMX8Lah3FcsYBo19CtbOpsU/qAYUDJOJBOrWwbNQbek="

before_install:
  # Install miniconda and create TEST env.
  - |
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update --quiet conda
    conda config --add channels conda-forge --force
    conda config --set channel_priority strict
    conda create --name TEST python=3 rb-bundler compilers doctr
    source activate TEST
    rm -f miniconda.sh
    bundle install

install:
  - bundle exec jekyll build --verbose

script:
  - |
    if [[ -z "$TRAVIS_TAG" ]]; then
      DEPLOY_DIR=dev
    else
      DEPLOY_DIR="$TRAVIS_TAG"
    fi

    if [[ "${TRAVIS_BRANCH}" == "source" ]]; then
      python -m doctr deploy --branch-whitelist source --key-path github_deploy_key_oceanhackweek_oceanhackweek_github_io.enc --built-docs _site/ .
    elif [[ "${TRAVIS_BRANCH}" == "draft" ]]; then
      python -m doctr deploy --branch-whitelist draft --key-path github_deploy_key_oceanhackweek_oceanhackweek_github_io.enc --built-docs _site/ draft
    fi
    python -m doctr deploy --branch-whitelist draft --build-tags --key-path github_deploy_key_oceanhackweek_oceanhackweek_github_io.enc --built-docs _site/ $DEPLOY_DIR
